services:
  books-service:
    container_name: books-service
    build:
      context: ./
      args:
        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/books
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - kotlin-spring

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=books
    networks:
      - kotlin-spring

networks:
  kotlin-spring: